package com.example.cabbooking.utilities;

import java.util.Random;

/**
 * Utility class for OTP generation and validation
 */
public class OTPGenerator {
    
    private static final int OTP_LENGTH = 4;
    private static final String NUMBERS = "0123456789";
    
    /**
     * Generate a random 4-digit OTP
     * @return String containing 4-digit OTP
     */
    public static String generateOTP() {
        Random random = new Random();
        StringBuilder otp = new StringBuilder();
        
        for (int i = 0; i < OTP_LENGTH; i++) {
            otp.append(NUMBERS.charAt(random.nextInt(NUMBERS.length())));
        }
        
        return otp.toString();
    }
    
    /**
     * Validate if entered OTP matches the generated OTP
     * @param enteredOTP OTP entered by user
     * @param actualOTP Actual OTP generated by system
     * @return true if OTPs match, false otherwise
     */
    public static boolean validateOTP(String enteredOTP, String actualOTP) {
        if (enteredOTP == null || actualOTP == null) {
            return false;
        }
        
        return enteredOTP.trim().equals(actualOTP.trim());
    }
    
    /**
     * Check if OTP format is valid (4 digits)
     * @param otp OTP to validate
     * @return true if format is valid, false otherwise
     */
    public static boolean isValidOTPFormat(String otp) {
        if (otp == null || otp.trim().isEmpty()) {
            return false;
        }
        
        String trimmedOTP = otp.trim();
        return trimmedOTP.length() == OTP_LENGTH && trimmedOTP.matches("\\d{" + OTP_LENGTH + "}");
    }
} 